// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// MessageMarginType message margin type
//
// swagger:model message.MarginType
type MessageMarginType int64

// for schema
var messageMarginTypeEnum []interface{}

func init() {
	var res []MessageMarginType
	if err := json.Unmarshal([]byte(`[0,1]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		messageMarginTypeEnum = append(messageMarginTypeEnum, v)
	}
}

func (m MessageMarginType) validateMessageMarginTypeEnum(path, location string, value MessageMarginType) error {
	if err := validate.EnumCase(path, location, value, messageMarginTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this message margin type
func (m MessageMarginType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateMessageMarginTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this message margin type based on context it is used
func (m MessageMarginType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
