// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tradeparadex/api/models"
)

// GetPositionsWithFilterReader is a Reader for the GetPositionsWithFilter structure.
type GetPositionsWithFilterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPositionsWithFilterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPositionsWithFilterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /positions-history] get-positions-with-filter", response, response.Code())
	}
}

// NewGetPositionsWithFilterOK creates a GetPositionsWithFilterOK with default headers values
func NewGetPositionsWithFilterOK() *GetPositionsWithFilterOK {
	return &GetPositionsWithFilterOK{}
}

/*
GetPositionsWithFilterOK describes a response with status code 200, with default header values.

OK
*/
type GetPositionsWithFilterOK struct {
	Payload *models.ResponsesGetPositionsHistoryResp
}

// IsSuccess returns true when this get positions with filter o k response has a 2xx status code
func (o *GetPositionsWithFilterOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get positions with filter o k response has a 3xx status code
func (o *GetPositionsWithFilterOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get positions with filter o k response has a 4xx status code
func (o *GetPositionsWithFilterOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get positions with filter o k response has a 5xx status code
func (o *GetPositionsWithFilterOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get positions with filter o k response a status code equal to that given
func (o *GetPositionsWithFilterOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get positions with filter o k response
func (o *GetPositionsWithFilterOK) Code() int {
	return 200
}

func (o *GetPositionsWithFilterOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /positions-history][%d] getPositionsWithFilterOK %s", 200, payload)
}

func (o *GetPositionsWithFilterOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /positions-history][%d] getPositionsWithFilterOK %s", 200, payload)
}

func (o *GetPositionsWithFilterOK) GetPayload() *models.ResponsesGetPositionsHistoryResp {
	return o.Payload
}

func (o *GetPositionsWithFilterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesGetPositionsHistoryResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
