// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetPositionsWithFilterParams creates a new GetPositionsWithFilterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPositionsWithFilterParams() *GetPositionsWithFilterParams {
	return &GetPositionsWithFilterParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPositionsWithFilterParamsWithTimeout creates a new GetPositionsWithFilterParams object
// with the ability to set a timeout on a request.
func NewGetPositionsWithFilterParamsWithTimeout(timeout time.Duration) *GetPositionsWithFilterParams {
	return &GetPositionsWithFilterParams{
		timeout: timeout,
	}
}

// NewGetPositionsWithFilterParamsWithContext creates a new GetPositionsWithFilterParams object
// with the ability to set a context for a request.
func NewGetPositionsWithFilterParamsWithContext(ctx context.Context) *GetPositionsWithFilterParams {
	return &GetPositionsWithFilterParams{
		Context: ctx,
	}
}

// NewGetPositionsWithFilterParamsWithHTTPClient creates a new GetPositionsWithFilterParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPositionsWithFilterParamsWithHTTPClient(client *http.Client) *GetPositionsWithFilterParams {
	return &GetPositionsWithFilterParams{
		HTTPClient: client,
	}
}

/*
GetPositionsWithFilterParams contains all the parameters to send to the API endpoint

	for the get positions with filter operation.

	Typically these are written to a http.Request.
*/
type GetPositionsWithFilterParams struct {

	/* Cursor.

	   Returns the ‘next’ paginated page.
	*/
	Cursor *string

	/* EndAt.

	   End Time (unix time millisecond)
	*/
	EndAt *int64

	// Market.
	Market *string

	/* PageSize.

	   Limit the number of responses in the page

	   Default: 100
	*/
	PageSize *int64

	// Side.
	Side *string

	/* StartAt.

	   Start Time (unix time millisecond)
	*/
	StartAt *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get positions with filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPositionsWithFilterParams) WithDefaults() *GetPositionsWithFilterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get positions with filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPositionsWithFilterParams) SetDefaults() {
	var (
		pageSizeDefault = int64(100)
	)

	val := GetPositionsWithFilterParams{
		PageSize: &pageSizeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get positions with filter params
func (o *GetPositionsWithFilterParams) WithTimeout(timeout time.Duration) *GetPositionsWithFilterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get positions with filter params
func (o *GetPositionsWithFilterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get positions with filter params
func (o *GetPositionsWithFilterParams) WithContext(ctx context.Context) *GetPositionsWithFilterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get positions with filter params
func (o *GetPositionsWithFilterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get positions with filter params
func (o *GetPositionsWithFilterParams) WithHTTPClient(client *http.Client) *GetPositionsWithFilterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get positions with filter params
func (o *GetPositionsWithFilterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCursor adds the cursor to the get positions with filter params
func (o *GetPositionsWithFilterParams) WithCursor(cursor *string) *GetPositionsWithFilterParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the get positions with filter params
func (o *GetPositionsWithFilterParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithEndAt adds the endAt to the get positions with filter params
func (o *GetPositionsWithFilterParams) WithEndAt(endAt *int64) *GetPositionsWithFilterParams {
	o.SetEndAt(endAt)
	return o
}

// SetEndAt adds the endAt to the get positions with filter params
func (o *GetPositionsWithFilterParams) SetEndAt(endAt *int64) {
	o.EndAt = endAt
}

// WithMarket adds the market to the get positions with filter params
func (o *GetPositionsWithFilterParams) WithMarket(market *string) *GetPositionsWithFilterParams {
	o.SetMarket(market)
	return o
}

// SetMarket adds the market to the get positions with filter params
func (o *GetPositionsWithFilterParams) SetMarket(market *string) {
	o.Market = market
}

// WithPageSize adds the pageSize to the get positions with filter params
func (o *GetPositionsWithFilterParams) WithPageSize(pageSize *int64) *GetPositionsWithFilterParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get positions with filter params
func (o *GetPositionsWithFilterParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithSide adds the side to the get positions with filter params
func (o *GetPositionsWithFilterParams) WithSide(side *string) *GetPositionsWithFilterParams {
	o.SetSide(side)
	return o
}

// SetSide adds the side to the get positions with filter params
func (o *GetPositionsWithFilterParams) SetSide(side *string) {
	o.Side = side
}

// WithStartAt adds the startAt to the get positions with filter params
func (o *GetPositionsWithFilterParams) WithStartAt(startAt *int64) *GetPositionsWithFilterParams {
	o.SetStartAt(startAt)
	return o
}

// SetStartAt adds the startAt to the get positions with filter params
func (o *GetPositionsWithFilterParams) SetStartAt(startAt *int64) {
	o.StartAt = startAt
}

// WriteToRequest writes these params to a swagger request
func (o *GetPositionsWithFilterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string

		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {

			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}
	}

	if o.EndAt != nil {

		// query param end_at
		var qrEndAt int64

		if o.EndAt != nil {
			qrEndAt = *o.EndAt
		}
		qEndAt := swag.FormatInt64(qrEndAt)
		if qEndAt != "" {

			if err := r.SetQueryParam("end_at", qEndAt); err != nil {
				return err
			}
		}
	}

	if o.Market != nil {

		// query param market
		var qrMarket string

		if o.Market != nil {
			qrMarket = *o.Market
		}
		qMarket := qrMarket
		if qMarket != "" {

			if err := r.SetQueryParam("market", qMarket); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.Side != nil {

		// query param side
		var qrSide string

		if o.Side != nil {
			qrSide = *o.Side
		}
		qSide := qrSide
		if qSide != "" {

			if err := r.SetQueryParam("side", qSide); err != nil {
				return err
			}
		}
	}

	if o.StartAt != nil {

		// query param start_at
		var qrStartAt int64

		if o.StartAt != nil {
			qrStartAt = *o.StartAt
		}
		qStartAt := swag.FormatInt64(qrStartAt)
		if qStartAt != "" {

			if err := r.SetQueryParam("start_at", qStartAt); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
